# Generated by Django 6.0.3 on 2026-07-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="position",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="list",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to="kanban.board",
            ),
        ),
    ]
