# Generated by Django 6.0.3 on 2026-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_alter_card_position_alter_list_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="background_color",
            field=models.CharField(blank=True),
        ),
    ]
