# Generated by Django 6.0.3 on 2026-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_board_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="background_image_url",
            field=models.URLField(blank=True, max_length=10000),
        ),
    ]
