# Generated by Django 6.0.3 on 2026-07-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0004_board_background_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="board",
            name="updated_count",
            field=models.IntegerField(default=0),
        ),
    ]
