# Generated by Django 6.0.3 on 2026-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0005_alter_card_options_alter_list_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="position",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
