# Generated by Django 6.0.3 on 2026-08-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0006_alter_card_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="position",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
