# Generated by Django 6.0.3 on 2026-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(blank=True, max_length=2000)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("category", models.CharField(blank=True, max_length=999)),
                ("name", models.CharField(blank=True, max_length=999)),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateField(auto_now=True)),
                ("counter", models.IntegerField(blank=True, default=-1)),
                ("display", models.BooleanField(default=True)),
            ],
        ),
    ]
