# Generated by Django 6.0.3 on 2026-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_for_later", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
