# Generated by Django 5.2.12 on 2026-03-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_for_later", "0002_media_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
