# Generated by Django 6.0.3 on 2026-03-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_for_later", "0003_alter_media_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
