# Generated by Django 5.2.13 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_for_later", "0008_alter_apikey_id_alter_category_id_alter_media_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="image_url",
            field=models.URLField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="media",
            name="link",
            field=models.URLField(blank=True, max_length=10000),
        ),
    ]
