# Generated by Django 6.0.3 on 2026-04-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "saved_for_later",
            "0009_alter_apikey_id_alter_category_id_alter_media_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
