# Generated by Django 6.0.3 on 2026-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_for_later", "0010_alter_apikey_id_alter_category_id_alter_media_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
